services:
  reportHubDbMongo:
    container_name: reportHubDb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
        - "27018:27017"
    volumes:
      - reportHubMongo_vol:/data/db    