using ReportHub.Application.Features.DataImports.Queries.CsvQueries;

namespace ReportHub.Application.Validators.DataImportQueryValidators.CsvQueryValidators;

public class InvoiceImportAsCsvQueryValidator : ImportQueryAsCsvQueryBaseValidator<InvoiceImportAsCsvQuery>{}
